In [11]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.linear_model import LinearRegression

In [49]:
df = pd.read_csv('dataset3.csv')
df.columns = df.columns.str.replace(' ', '')
df

,type,fixedacidity,volatileacidity,citricacid,residualsugar,chlorides,freesulfurdioxide,totalsulfurdioxide,density,pH,sulphates,alcohol,quality
0,white,7.0,0.270,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6
1,white,6.3,0.300,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6
2,white,8.1,0.280,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6
3,white,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
4,white,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,red,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
6493,red,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,NaN,11.2,6
6494,red,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
6495,red,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
6496,red,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [63]:
import math
median_fixedacidity=math.floor(df.fixedacidity.median())
median_volatileacidity=math.floor(df.volatileacidity.median())
median_citricacid=math.floor(df.citricacid.median())
median_residualsugar=math.floor(df.residualsugar.median())
median_chlorides=math.floor(df.chlorides.median())
median_pH=math.floor(df.pH.median())
median_sulphates=math.floor(df.sulphates.median())


median_fixedacidity
median_volatileacidity
median_citricacid
median_residualsugar
median_chlorides
median_pH
median_sulphates

0

In [64]:
df.fixedacidity=df.fixedacidity.fillna(median_fixedacidity)
df.volatileacidity=df.volatileacidity.fillna(median_volatileacidity)
df.citricacid=df.citricacid.fillna(median_citricacid)
df.residualsugar=df.residualsugar.fillna(median_residualsugar)
df.chlorides=df.chlorides.fillna(median_chlorides)
df.pH=df.pH.fillna(median_pH)
df.sulphates=df.sulphates.fillna(median_sulphates)
df

,type,fixedacidity,volatileacidity,citricacid,residualsugar,chlorides,freesulfurdioxide,totalsulfurdioxide,density,pH,sulphates,alcohol,quality
0,white,7.0,0.270,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6
1,white,6.3,0.300,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6
2,white,8.1,0.280,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6
3,white,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
4,white,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,red,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
6493,red,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.00,11.2,6
6494,red,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
6495,red,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
6496,red,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [65]:
y = df[{'fixedacidity'}]

In [66]:
x = df.drop(['type', 'fixedacidity'], axis =1)

In [67]:
x

,volatileacidity,citricacid,residualsugar,chlorides,freesulfurdioxide,totalsulfurdioxide,density,pH,sulphates,alcohol,quality
0,0.270,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6
1,0.300,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6
2,0.280,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6
3,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
4,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
...,...,...,...,...,...,...,...,...,...,...,...
6492,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
6493,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.00,11.2,6
6494,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
6495,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
6496,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [68]:
from sklearn.model_selection import train_test_split

In [69]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.3)

In [70]:
lr = LinearRegression()

In [72]:
lr.fit(x_train, y_train)

LinearRegression()

In [73]:
print(lr.coef_)

[[-6.48318030e-01  1.25154692e+00 -2.43133239e-01 -3.57453894e+00
  -1.25620686e-03  1.39952798e-04  6.14840008e+02 -3.95026933e+00
  -8.58294915e-01  6.35018036e-01  4.16788081e-02]]

In [74]:
print(lr.intercept_)

[-596.73536899]

In [75]:
y_pred = lr.predict(x)
print('predicted response:', y_pred, sep='\n')

predicted response:
[[7.36973084]
 [6.90964126]
 [6.93878242]
 ...
 [7.53740471]
 [6.23676337]
 [7.86483471]]

In [76]:
from sklearn.metrics import mean_squared_error 
  
# # Given values 
# Y_true = [2,4,5,4,5]  # Y_true = Y (original values) 
  
# # calculated values 
# Y_pred = [2.8,3.4,4,4.6,5.2]  # Y_pred = Y' 
  
# Calculation of Mean Squared Error (MSE) 
mean_squared_error(y,y_pred)

0.3463966638169181

In [77]:
RSS = np.sum((y-y_pred)**2)
print("Residual sum of squares: %.2f" % RSS)

Residual sum of squares: 2250.54